# Use root/example as user/password credentials
version: '3.1'

services:
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_DATABASEL: mongo
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - 27017:27017