from dotenv import load_dotenv
import os

load_dotenv()

# FASTAPI
FAST_API_APP_PORT=os.getenv("FAST_API_APP_PORT")

# MESSAGE BROKERS
IMAGE_RESOLUTION_MB_TOPIC = os.getenv("IMAGE_RESOLUTION_MB_TOPIC")
IMAGE_RESOLUTION_MB_BOOTSTRAP_SERVERS = os.getenv("IMAGE_RESOLUTION_MB_BOOTSTRAP_SERVERS")
IMAGE_RESOLUTION_MB_GROUP_ID = os.getenv("IMAGE_RESOLUTION_MB_GROUP_ID")
# OBJECT STORAGE
